Project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('leaderboard.urls'))
]

leaderboard/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.Index.as_view(), name='home'),
    path('player/<int:pk>/', views.DashboardView.as_view(), name='dashboard')
]

leaderboard/models.py
from leaderboard.managers import PlayerManager
from django.db import models
from django.db.models import F
from django.db.models.signals import pre_save, post_save
from django.dispatch import receiver
from mojang import MojangAPI


class Player(models.Model):
    name = models.CharField(max_length=256)
    uuid = models.CharField(
        max_length=32, blank=True)
    imageUrl = models.URLField(
        default='https://www.mc-heads.net/avatar/MHF_Steve/32')
    event01 = models.IntegerField(default=0)
    event02 = models.IntegerField(default=0)
    event03 = models.IntegerField(default=0)
    event04 = models.IntegerField(default=0)
    event05 = models.IntegerField(default=0)
    event06 = models.IntegerField(default=0)
    event07 = models.IntegerField(default=0)
    event08 = models.IntegerField(default=0)
    event09 = models.IntegerField(default=0)
    event10 = models.IntegerField(default=0)
    event11 = models.IntegerField(default=0)
    event12 = models.IntegerField(default=0)
    _total = None

    objects = PlayerManager(
        total=F('event01') + F('event02') + F('event03') +
        F('event04') + F('event05') + F('event06') +
        F('event07') + F('event08') + F('event09') +
        F('event10') + F('event11') + F('event12'),
    )

    def __str__(self):
        return self.name


@receiver(pre_save, sender=Player)
def get_data(sender, instance, *args, **kwargs):
    instance.uuid = MojangAPI.get_uuid(instance.name)
    instance.imageUrl = (f"https://www.mc-heads.net/avatar/{instance.uuid}/32")

leaderboard/forms.py
from django import forms
from django.forms.widgets import HiddenInput
from .models import Player

class PlayerUpdateForm(forms.ModelForm):
    class Meta:
        model = Player
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget = HiddenInput()
        self.fields['uuid'].widget = HiddenInput()
        self.fields['imageUrl'].widget = HiddenInput()
        self.fields['event01'].widget.attrs.update({'class':'form-control', 'style': ' background-color: #212121; color: #FFFFFF;'})
        self.fields['event02'].widget.attrs.update({'class':'form-control', 'style': ' background-color: #212121; color: #FFFFFF;'})
        self.fields['event03'].widget.attrs.update({'class':'form-control', 'style': ' background-color: #212121; color: #FFFFFF;'})
        self.fields['event04'].widget.attrs.update({'class':'form-control', 'style': ' background-color: #212121; color: #FFFFFF;'})
        self.fields['event05'].widget.attrs.update({'class':'form-control', 'style': ' background-color: #212121; color: #FFFFFF;'})
        self.fields['event06'].widget.attrs.update({'class':'form-control', 'style': ' background-color: #212121; color: #FFFFFF;'})
        self.fields['event07'].widget.attrs.update({'class':'form-control', 'style': ' background-color: #212121; color: #FFFFFF;'})
        self.fields['event08'].widget.attrs.update({'class':'form-control', 'style': ' background-color: #212121; color: #FFFFFF;'})
        self.fields['event09'].widget.attrs.update({'class':'form-control', 'style': ' background-color: #212121; color: #FFFFFF;'})
        self.fields['event10'].widget.attrs.update({'class':'form-control', 'style': ' background-color: #212121; color: #FFFFFF;'})
        self.fields['event11'].widget.attrs.update({'class':'form-control', 'style': ' background-color: #212121; color: #FFFFFF;'})
        self.fields['event12'].widget.attrs.update({'class':'form-control', 'style': ' background-color: #212121; color: #FFFFFF;'})

leaderboard/views.py
from leaderboard.forms import PlayerUpdateForm
from leaderboard.models import Player
from django.views import generic
from django.urls import reverse_lazy
from django.db.models import Max


class Index(generic.ListView):
    model = Player
    template_name = 'leaderboard/index.html'
    paginate_by = 20
    ordering = ['-total']


class DashboardView(generic.UpdateView):
    model = Player
    form_class = PlayerUpdateForm
    template_name = 'leaderboard/dashboard.html'
    success_url = reverse_lazy('home')

leaderboard/templates/leaderboard/dashboard.html
{% extends 'base.html' %}

{% block title %}Edit {{player.name}}{% endblock %}

{% block content %}

<div class="m-5" style="color: white;">
    <h3>Update Player Data</h3>
</div>

<div class="card m-5" style="background-color: #202020; color: white;">
    <div class="card-body mx-3">
        <h5 class="text-center">
            <img src="{{ player.imageUrl }}" 
            width="32" height="32" /> {{ player.name }}
        </h5>
        <form method="post" style="margin-top: 1.3em;">

            {{ form.as_p }}

            {% csrf_token %}

            <div class="mt-3">
                <button type="submit" class="btn btn-outline-light">Submit</button>
            </div>
        </form> 
    </div>
</div>

{% endblock content %}

leaderboard/templates/leaderboard/index.html
{% extends 'base.html' %} 

{% block title %}Leaderboard{% endblock %} 

{% block content %}
<div class="card m-3" style="background-color: #202020; margin-top: auto">
  <div class="card-body">
    <div class="responsiveWrap" style="overflow-x: auto;">
      <table class="table table-borderless table-dark table-striped table-hover table-responsive-stack">
        <thead class="text-center">
          <tr>
            <th scope="col">Pos</th>
            <th class="text-start" scope="col">Name</th>
            <th scope="col">Score</th>
            <th scope="col">Dropper</th>
            <th scope="col">Death to Merchants</th>
            <th scope="col">Decapitation Station</th>
            <th scope="col">Phantom Menace</th>
            <th scope="col">The Kingdom Games</th>
            <!-- <th scope="col">Event 06</th>
            <th scope="col">Event 07</th>
            <th scope="col">Event 08</th>
            <th scope="col">Event 09</th>
            <th scope="col">Event 10</th>
            <th scope="col">Event 11</th>
            <th scope="col">Event 12</th> -->
            {% if user.is_superuser %}
            <th>Actions</th>
            {% endif %}
          </tr>
        </thead>
        <tbody class="text-center">
          {% for player in player_list %}
            <tr>
              {% if forloop.counter == 1 %}
              <td><i class="fas fa-trophy" style="color: gold;"></i> {{ forloop.counter }}</td>
              {% else %}
              <td>{{ forloop.counter }}</td>
              {% endif %}
              <td class="text-start">
                <img src="{{ player.imageUrl }}" alt="" 
                 width="16" height="16" /> {{ player.name }}
              </td>
              <td>{{ player.total }}</td>
              <td>{{ player.event01 }}</td>
              <td>{{ player.event02 }}</td>
              <td>{{ player.event03 }}</td>
              <td>{{ player.event04 }}</td>
              <td>{{ player.event05 }}</td>
              <!-- <td>{{ player.event06 }}</td>
              <td>{{ player.event07 }}</td>
              <td>{{ player.event08 }}</td>
              <td>{{ player.event09 }}</td>
              <td>{{ player.event10 }}</td>
              <td>{{ player.event11 }}</td>
              <td>{{ player.event12 }}</td> -->
              {% if user.is_superuser %}
                <td class="text-center">
                  <a href="{% url 'dashboard' player.id %}"
                    ><i class="fas fa-edit" style="color: #ffffff;"></i
                  ></a>
                </td>
              {% endif %}
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %} 


{% block pagination %} 
  {% if is_paginated %}
    <div class="m-3">
      <div class="pagination">
        <span class="page-links">
          {% if page_obj.has_previous %}
          <a
            class="btn btn-outline-light btn-sm"
            href="{{ request.path }}?page={{ page_obj.previous_page_number }}"
            >&larr;</a
          >
          {% endif %} {% if page_obj.has_next %}
          <a
            class="btn btn-outline-light btn-sm"
            href="{{ request.path }}?page={{ page_obj.next_page_number }}"
            >&rarr;</a
          >
          {% endif %}
        </span>
      </div>
    </div>
  {% endif %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    {% block meta %}{% endblock %}

    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We"
      crossorigin="anonymous"
    />

    <title>{% block title %}{% endblock %} • The Ebrius Games</title>
  </head>
  <body>
    <!-- Header -->
    {% include 'snippets/base_css.html' %} {% include 'snippets/header.html' %}

    <style type="text/css">
      .main {
        min-height: 100vh;
        height: 100%;
      }
    </style>

    <div class="main">
      {% block content %}{% endblock %} {% block pagination %}{% endblock %}
    </div>

    <!-- Footer -->
    {% include 'snippets/footer.html' %}

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj"
      crossorigin="anonymous"
    ></script>
    <script src="https://kit.fontawesome.com/308813b2e2.js" crossorigin="anonymous"></script>
    <!-- <script src="https://unpkg.com/feather-icons"></script>
    <script>
      feather.replace()
    </script>     -->
    {% block js %}{% endblock %}
  </body>
</html>

templates/snippets/base_css.html
<style type="text/css">
    body{
        background-color: #181818;
    }

    :root{
        --main-background-color: #181818;
        --dark-background-color: #202020;
        --secondary-text-color: #AAAAAA;
        --light-primary-text-color: #FFFFFF;
    }
</style>

templates/snippets/footer.html
<footer class="bg-light text-center text-lg-start">
	<!-- Copyright -->
	<div class="text-center p-3" style="background-color: #202020">
	  <a class="text-light" href="https://www.ebrius.xyz">Ebrius SMP | 2021</a>
	</div>
	<!-- Copyright -->
  </footer>

templates/snippets/header.html
<header class="d-flex justify-content-center py-3" style="background-color: #202020 ">
  <ul class="nav nav-pills">
    <li class="nav-item"><a href="{% url 'home' %}" class="nav-link" aria-current="page" style="color: #FFFFFF;"><b>The Ebrius Games</b></a></li>
  </ul>
</header>